/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazzle;

import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Hello World! It's a test :)";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
