package wazzle.model.maingame.grid;

import java.util.Set;
import wazzle.model.maingame.letter.Letter;

/**
 * Represents an interface for modeling a grid object. A grid contains a {@code Set<Letter>}
 * previously generated by {@link wazzle.model.maingame.letter.LetterAllocator}. This interface
 * provides some methods for retrieving informations about the grid object.
 *
 * @see wazzle.model.maingame.letter.Letter
 * @see wazzle.model.maingame.letter.LetterAllocator
 */
public interface Grid {

  /**
   * Returns the set of letters that this grid contains.
   *
   * @return {@code Set<Letter>} the letters contained in this grid.
   * @see wazzle.model.maingame.letter.Letter
   * @see java.util.Set
   */
  Set<Letter> getLetters();

  /**
   * Returns the set of {@code String} describing all the words you can find inside this grid.
   *
   * @return {@code Set<String>} the words contained in this grid.
   * @see java.util.Set
   */
  Set<String> getWordsCanBeFound();

  /**
   * Returns the sum of all the single @{code Letter} score inside this grid.
   *
   * @return {@code int} the grid total score.
   */
  int getTotalScore();
}
