/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazzle;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    assertTrue(true);
  }
}
